services:
  postgres:
    container_name: postgres
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=modulith_demo'
      - 'POSTGRES_PASSWORD=modulith'
      - 'POSTGRES_USER=modulith'
    ports:
      - "5432:5432"

    volumes:
      - /c/tmp/postgres_modulith:/var/lib/postgresql/data


volumes:
  postgres:

